### ISSUE TITLE
Possible bug in circuits/min.json

### ISSUE THREAD

**Issue by alessiofiorin** [ojroques/Garbled-Circuit#3]
Hi!
I think there is a bug in  circuits/min.json because some results of minimum function are incorrect.
I suppose that instead of `{"id": 10, "type": "OR", "in": [1, 3]}`, it is `{"id": 10, "type": "AND", "in": [1, 3]}`.

Thanks!

**Comment by ojroques** [comment]
Yes you're right. It's fixed now, thanks for pointing it out!
