### ISSUE TITLE
Question about p-bits

### ISSUE THREAD

**Issue by seafooler** [ojroques/Garbled-Circuit#4]
Thanks for your wonderful codes.
I'm a newbie to garbled-circuit. Although I have tried my best, I cannot understand what the `p-bits` in the codes are used for and I find no description of `p-bits` in this link [Garbled circuit](https://en.wikipedia.org/wiki/Garbled_circuit).

Could you kindly give me some clues about `p-bits`?

Many thanks in advance.

**Comment by ojroques** [comment]
Hello,

The p-bits are also sometimes called "color bits". Each wire in the circuit has one, and they are used to basically permute the garbled tables. A nice explanation is available here: https://crypto.stackexchange.com/a/48091 (section "Permute-and-point").
